### ISSUE TITLE
JISEC operation for notes on FCS family

### ISSUE THREAD

**Issue by Ryuichiro-Ohya-FX** [HCD-iTC/HCD-iTC-Template#362] opened 2024-08-15 03:46 UTC
**Requesting Organization:**
ryuichiro.ohya.jz@fujifilm.com

**Status:**
This issue is not related to CC evaluation for any actual products. This issue should be a kind of concern for the future products.  

[ ] On-going certification
[x] Preparatory/Other

**Document Affected**
HCD cPP v1.0e, HCD SD v1.0e

**Certification Deadline Dates:**
N/A

**Section of HCD cPP/HCD SD in question (reference to SFR or subchapter in the HCD cPP or HCD SD):**
FPT_SBT_EXT.1.5

**Supporting Document testing in question:**
The following notes on FCS_COP.1/xxxs.
"Note: Testing of cryptographic functions implemented in the Root of Trust for Secure Boot
(FPT_SBT_EXT.1) may not be feasible and independent testing may not be available. In this
situation, contact the CC Scheme."

**Issue:**
As the result of addition of the above note to FCS_COP.1/xxx in HCD cPP v1.0e, JISEC introduced the attached operation, which requires manufacturers to describe the information to identify the Root of Trust product or implementation in TSS. We, Japanese manufacturers accepted it once, but still have a concern about this operation because such kind of information should be sensitive to be disclosed. We manufacturer asked with JISEC if it is acceptable to describe the information in KMD or something else which is not disclosed publicly, but the answer was negative because they think the public disclosure of the information should deter false claims by manufacturers.

**Proposed Resolution(if any):**
Remove the notes added to FCS_COP.1/xxx, or modify FPT_SBT_EXT.1.5 so that it requires only to ensure the authenticity by Root of Trust instead of requiring selection of specific cryptographic method.
A JISEC person mentioned that CC manner requires evaluator to verify the validity of the implementation for the claimed SFR. So, he believes that if FPT_SBT_EXT.1.5 requires the detailed cryptographic method and if verification cannot be done for the immutable RoT, then the additional notes are reasonable. And he mentioned that the additional notes can be removed if FPT_SBT_EXT.1.5 can be more abstract requirements, like "just ensure the authenticity of each chain of trust."

**Rationale:**
N/A

[JISEC interpretation on RoT testing.docx](https://github.com/user-attachments/files/16620850/JISEC.interpretation.on.RoT.testing.docx)

**Comment by Ryuichiro-Ohya-FX** [comment] 2024-08-16 00:43
I moved this issue into the HIT-IT repository.

**Comment by gcolunga** [comment] 2024-08-19 19:20
Closing this issue as a duplicate of https://github.com/HCD-iTC/HCD-IT/issues/26.

**Closed as completed by gcolunga** 2024-08-19 19:20 UTC
Labels: Interpretation
